### ISSUE TITLE
issue with grep

### ISSUE THREAD

**Issue by the-tech-mode** [rahimrajwani/MIRU-profiler#1]
Hello Im very interested in using MIRU-profiler, however Im having a problem when I try to run the program 

this is the command im typing and the 'error' message: 

iMac:~ b609$ cd /Users/b609/Downloads/MIRU-profiler-master 
iMac:MIRU-profiler-master b609$ ./MIRU-profiler -i '/Users/b609/Downloads/input_dir/H37Rv.fasta'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
/MIRU-profiler: line 73: 1s: command not found
./MIRU-profiler: line 74: 2s: command not found
./MIRU-profiler: line 75: 3s: command not found
./MIRU-profiler: line 76: 4s: command not found
./MIRU-profiler: line 77: 5s: command not found
./MIRU-profiler: line 78: 6s: command not found
./MIRU-profiler: line 79: 7s: command not fo......
........
......
...
..

Is there any other dependency I need to install? 
I had isntall emboss already via conda with this command 

conda install -c bioconda emboss 

Does it has somethong to do?

I would appreciate your help 
thanks 

Hector

**Comment by rahimrajwani** [comment]
Hi Hector

Thanks for your interest in MIRU-profiler. The program is designed for linux/Ubuntu. If you are trying to run it on Mac, it may not work.

**Comment by jamalsaad1** [comment]
Hi Dr rahimrajwani,

I have question, about Not detected and unknown alleles number.
How can I analyze our genome with these two word ( for example if i want design phylogenetic tree I can not because i need number in the output table).
