### ISSUE TITLE
Perimission Denied

### ISSUE THREAD

**Issue by the-tech-mode** [rahimrajwani/MIRU-profiler#2]
Hello! trying to run the program from a Ubuntu mini server I got this message 
do you have idea how to solve ir?
Im running from the administrator account

luna2@luna:~/Downloads/MIRU-profiler-master$ cd
luna2@luna:~$ cd '/home/luna2/MIRU-profiler-master' 
luna2@luna:~/MIRU-profiler-master$ ./MIRU-profiler -i '/home/luna2/Desktop/denovol/H37Rv/H37Rv.fa' 
bash: ./MIRU-profiler: Permission denied
luna2@luna:~/MIRU-profiler-master$ ./MIRU-profiler -h
bash: ./MIRU-profiler: Permission denied
luna2@luna:~/MIRU-profiler-master$

thanks a lot

**Comment by rahimrajwani** [comment]
Hi Hector,

It seems that the script do not have the permission to execute on the server you are using. Try changing the permissions for the script using chmod.

In addition, you might need the emboss program on your server to make it work.

**Comment by the-tech-mode** [comment]
I used "chmod 1777" to modify the permission on the file  MIRU-profiler
now it is working!
Thank you very much!!
